apiVersion: "authentication.istio.io/v1alpha1"
kind: "Policy"
metadata:
  name: default
  namespace: api-private
spec:
  origins:
  - jwt:
      issuer: "auth@auth.app.com"
      jwksUri: "http://api.pollination.cloud/users/auth/public_key"
  originIsOptional: false
  principalBinding: USE_ORIGIN
---
