apiVersion: v1
kind: Namespace
metadata:
  name: api-public
  labels:
    istio-injection: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: api-private
  labels:
    istio-injection: enabled
