apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: webhook-sensor-http
  namespace: argo-events
  labels:
    sensors.argoproj.io/sensor-controller-instanceid: argo-events
spec:
  deploySpec:
    containers:
      - name: "sensor"
        image: "argoproj/sensor"
        imagePullPolicy: Always
    serviceAccountName: argo-events-sa
  dependencies:
    - name: "webhook-gateway-http:foo"
  eventProtocol:
    type: "HTTP"
    http:
      port: "9300"
  serviceSpec:
    metadata:
      name: webhook-sensor-http-svc
      namespace: argo-events
    spec:
      selector:
        name: webhook-sensor-http
      ports:
        - name: http
          port: 9300
          targetPort: 9300
      type: ClusterIP
  triggers:
    - name: webhook-workflow-trigger
      resource:
        namespace: assembly-line
        group: argoproj.io
        version: v1alpha1
        kind: Workflow
        source:
          inline: |
            apiVersion: argoproj.io/v1alpha1
            kind: Workflow
            metadata:
              generateName: hello-world-
              namespace: assembly-line
            spec:
              entrypoint: whalesay
              templates:
                - name: whalesay
                  container:
                    args:
                      - "hello world"
                    command:
                      - cowsay
                    image: "docker/whalesay:latest"