apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: webhook-sensor-http
  namespace: argo-events
  labels:
    sensors.argoproj.io/sensor-controller-instanceid: argo-events
spec:
  deploySpec:
    containers:
      - name: "sensor"
        image: "argoproj/sensor"
        imagePullPolicy: Always
    serviceAccountName: argo-events-sa
  dependencies:
    - name: "webhook-gateway-http:foo"
  eventProtocol:
    type: "HTTP"
    http:
      port: "9300"
  serviceSpec:
    metadata:
      name: webhook-sensor-http-svc
      namespace: argo-events
    spec:
      selector:
        name: webhook-sensor-http
      ports:
        - name: http
          port: 9300
          targetPort: 9300
      type: ClusterIP
  triggers:
    - name: webhook-workflow-trigger
      resource:
        namespace: assembly-line
        group: argoproj.io
        version: v1alpha1
        kind: Workflow
        parameters:
          - src:
              event: "webhook-gateway-http:foo"
              path: message
              value: "Didn't find it..."
            dest: spec.arguments.parameters.0.value
          - src:
              event: "webhook-gateway-http:foo"
            dest: spec.arguments.parameters.1.value
        source:
          inline: |
            apiVersion: argoproj.io/v1alpha1
            kind: Workflow
            metadata:
              generateName: hello-world-
              namespace: assembly-line
            spec:
              entrypoint: whalesay
              arguments:
                parameters:
                - name: message
                  # this is the value that should be overridden
                  value: hello world
                - name: second-message
                  value: goodbye world
              templates:
                - name: whalesay
                  inputs:
                    parameters:
                    - name: message
                    - name: second-message
                  container:
                    command: [cowsay]
                    image: "docker/whalesay:latest"
                    args: ["{{inputs.parameters.message}} AND unparsed {{inputs.parameters.second-message}}"]